Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyServiceDesk.Domain.Entities;
using MyServiceDesk.Models.ViewUsers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyServiceDesk.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> roleManager;
        UserManager<User> userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult Index() => View(roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await userManager.GetRolesAsync(user);
                var allRoles = roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await userManager.AddToRolesAsync(user, addedRoles);

                await userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using MyServiceDesk.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyServiceDesk.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;

        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }
            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyServiceDesk.Domain.Entities;
using MyServiceDesk.Models.ViewUsers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyServiceDesk.Controllers
{
    [Authorize(Roles="admin")]
    public class UsersController : Controller
    {
        UserManager<User> userManager;

        public UsersController(UserManager<User> userMgr)
        {
            this.userManager = userMgr;
        }

        public IActionResult Index() => View(userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { UserName = model.Login, Name = model.Name, SurName = model.SurName, MiddleName = model.MiddleName, Email = model.Email };
                var result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Name = user.Name, SurName = user.SurName, MiddleName = user.MiddleName, Email = user.Email, Login = user.UserName};
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Name = model.Name;
                    user.SurName = model.SurName;
                    user.MiddleName = model.MiddleName;
                    user.Email = model.Email;

                    var result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }

                    }
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true" />

Views/Shared/FooterPartial.cshtml
<!-- Footer -->
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div id="copyright">
                    &copy; @Config.CompanyName. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
                </div>

            </div>
        </div>
    </div>
</div>

Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <header id="header">
                    <h1><a href="/" id="logo">@Config.CompanyName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Наши услуги</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                            <a asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                        }
                    </nav>
                </header>
                @if (User.Identity.IsAuthenticated)
                {
                    <nav id="menu1">
                        <ul>
                            <li>
                                @if (User.IsInRole("admin"))
                                {
                                    <a href="">Панель Администратора @User.Identity.Name</a>
                                    <ul>
                                        <li><a asp-area="" asp-controller="Users" asp-action="Index" asp-route-id="">Пользователи</a></li>
                                        <li><a asp-area="" asp-controller="Roles" asp-action="Index" asp-route-id="">Роли</a></li>
                                        <li><a asp-area="" asp-controller="Admin" asp-action="Index" asp-route-id="">Админка</a></li>
                                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a></li>
                                    </ul>
                                }
                                else
                                {
                                    <a href="">Пользователь</a>
                                    <ul>
                                        <li><a asp-area="" asp-controller="Home" asp-action="UserInfo" asp-route-id="">Логин @User.Identity.Name</a></li>
                                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a></li>
                                    </ul>                                    
                                }
                            </li>
                        </ul>
                    </nav>
                }
                </div>
        </div>
    </div>
</div>

Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}

@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div id="page-wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium">
                        @RenderBody()
                    </div>
                    @await Html.PartialAsync("SidebarPartial")                                              
                </div>
            </div>
        </div>
        @await Html.PartialAsync("FooterPartial")
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>